name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Lnk2past/auto-grader-action@master
      id: grade
    - name: Get the build output
      run: echo "Build: ${{ steps.grade.outputs.build_output }}"
    - name: Get the test output
      run: echo "Test: ${{ steps.grade.outputs.test_output }}"
    - name: Get the score
      run: echo "Score: ${{ steps.grade.outputs.score }}"
